LARGURA_TELA = 800
ALTURA_TELA = 600
TITULO_JANELA = "Príncipe Dorminhoco"
CAMINHO_TEXTURA = "textura.jpg"
VOLUME_MUSICA = 0.5

MUSICA_POR_SALA = {
    "sala_1": "dorminho2.mp3",
    "corredor": "dorminho2.mp3",
    "sala_2": "dorminhogrande.mp3",
}

LARGURA_MUNDO = 1000
ALTURA_MUNDO = 750

ALFA_ESCURIDAO_AMBIENTE = 150
RAIO_LUZ_X = 70
RAIO_LUZ_Y = 70
PASSOS_LUZ = 28

MARGEM_VIEWPORT = 90
JOGADOR_INICIO_X = 500
JOGADOR_INICIO_Y = 440
SALA_INICIAL = "sala_1"
TAMANHO_FONTE_HUD = 22
